### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by janko-m** [eltiare/carrierwave-vips#24]
I've recently created a [image_processing](https://github.com/janko-m/image_processing) library, which is just a set of higher-level processing helper methods. This library was originally spawned as a byproduct of [Shrine](https://github.com/janko-m/shrine), but the idea was that it's completely generic and usable in any code and with any uploading libraries. Currently I have only MiniMagick processing, but I want to add VIPS as well (and later RMagick).

Your great library would be an awesome "inspiration" for that kind of addition. However, I see that there is no license for this library, and a default license is "all rights reserved". If this was MIT licensed, I was thinking to adapt your code to my library and ruby-vips8, and say in the README that it was adapted from carrierwave-vips. Is that something you would be ok with?

**Comment by eltiare** [comment]
Yeah, it's MIT licensed. I need to get around to putting that in.

**Comment by janko-m** [comment]
Ok, awesome, it'll probably need a lot of changing anyway since I'll be using ruby-vips8 which has a different API, but hopefully some parts of API stayed the same.

**Comment by eltiare** [comment]
Oh nice. I had no idea that version 8's been released. I might have interesting in making a new version myself in the near future. I haven't needed super-efficient image processing, but I may again soon.

**Comment by eltiare** [comment]
@janko-m You might be able to enlist @jcupitt's help, if he's involved with version 8.

**Comment by jcupitt** [comment]
I did a blog post on ruby-vips8: 

http://libvips.blogspot.co.uk/2016/01/ruby-vips-is-dead-long-live-ruby-vips8.html

It talks a bit about the differences and shows some examples. The general "shape" of your code will be the same, but many methods have been renamed or adjusted. 

ruby-vips was hand-made and had it's own distinct API. ruby-vips8 is largely automatically generated, so the API is pretty much the same as the vips8 bindings for C, C++, Python, command-line and JavaScript. This is a good thing, for me at least, since there's a lot less documentation and code to maintain. 

@janko-m, I'd be very happy to help, I've only used ruby-vips8 in my own projects, it'd be interesting to make it work with someone else's needs.

**Comment by eltiare** [comment]
License is added.

**Comment by janko-m** [comment]
@jcupitt Thank you for offering to help, and sorry for not answering sooner 😄. I still haven't got to adding VIPS support to [image_processing](https://github.com/janko-m/image_processing), but I think the latest PR to carrierwave-vips will help a great deal. If I have any questions, I'll be sure to let you know. Thank you for your work on VIPS and ruby-vips ❤️
